name: Build and publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Replace Version and Build Number
      id: repl
      run: |
        ls -la

    #- name: Build snap
    #  uses: snapcore/action-build@v1
    #  id: build
      
    #- name: Publish snap
    #  uses: snapcore/action-publish@v1
    #  env:
    #    SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    #  with:
    #    snap: ${{ steps.build.outputs.snap }}
    #    release: edge

