name: 4testing

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Snapcraft with LXD
        uses: samuelmeuli/action-snapcraft@v2
        with:
          use_lxd: ${{ matrix.os == 'ubuntu-18.04' }}
        - name: Build snap
        run: sg lxd -c 'snapcraft --use-lxd'

