name: Publish SNAP arfifact

run-name: Publish ONLYOFFICE_DesktopEditors-${{ github.event.inputs.version }}-${{ github.event.inputs.build }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true
      build:
        description: 'Build number'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get
      run: |
        VERSION=${{ github.event.inputs.version }}
        BUILD_NUMBER=${{ github.event.inputs.build }}
        #replace version
        QUERY="curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ONLYOFFICE/appimage-desktopeditors/actions/artifacts"
        JQ_QUERY=".artifacts.[] | select(.name | test("$VERSION-$BUILD_NUMBER"))"
        RESULT=`$QUERY`
        echo $RESULT

